version: "3"

services:
  go-carbon:
    build:
      dockerfile: docker/go-carbon/Dockerfile
      context: .
    ports:
      - "2003:2003"
    networks:
      testnet:
        ipv4_address: 172.25.25.13

  carbonapi:
    build:
      dockerfile: docker/carbonapi/Dockerfile
      context: .
    ports:
      - "7081:7081"
      - "8081:8081"
    networks:
      testnet:
        ipv4_address: 172.25.25.11
    links:
      - zipper

  zipper:
    build:
      dockerfile: docker/zipper/Dockerfile
      context: .
    volumes:
      - "./config/carbonzipper.yaml:/etc/carbonzipper.yaml"
    ports:
      - "7000:7000"
      - "8000:8000"
    networks:
      testnet:
        ipv4_address: 172.25.25.12
    links:
      - go-carbon

networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.25.0/24
